### ISSUE TITLE
linux_amd64 run failed

### ISSUE THREAD

**Issue by akkuman** [six-ddc/v2ex-go#3]
## environment：
- manjaro
- linux 64
- kde
## 执行时出错
```
┌�����������������������Tab [C-t]�����������������������───────────────────────────────────────────────────────────────────────────────────────────────────────────┌技术 创意────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│���� 创意 好玩 Apple 酷工作 交易 城市 问与答 最热�全部 R2 节点�关注                                                                                   �����������││����������������─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────│
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘┌�����������������������Reply [C-p]���������������������───────────────────────────────────────────────────────────────────────────────────────────────────────────┌���ic������──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
┌           ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│            (...)panic: runtime error: index out of range                                                                                                        │
│                                                                                                                                                                 │
goroutine 65 [running]:                                                                                                                                           │
panic(0x6a4b40, 0xc42000a110)                                                                                                                                     │
│       /usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1                                                                                        │
main.ParseTopicByTab.func3(0x0, 0xc42054b350)                                                                                                                     │
│       /Users/dudongcheng/Code/Up/go/src/github.com/six-ddc/v2ex-go/v2ex.go:134 +0x58a                                                                           │
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc42054b320, 0xc4201bfd08, 0xd)                                                                                 │
│       /Users/dudongcheng/Code/Up/go/src/github.com/PuerkitoBio/goquery/iteration.go:10 +0x101                                                                   │
main.ParseTopicByTab(0x6f708b, 0x3, 0xc42007b9e0, 0xc4202c4660, 0x2, 0x2, 0x0, 0x0, 0x0)                                                                          │
│       /Users/dudongcheng/Code/Up/go/src/github.com/six-ddc/v2ex-go/v2ex.go:146 +0x6a0                                                                           │
main.(*UITopicList).Fresh(0xc420170ea0, 0x6f708b, 0x3, 0x0, 0x0)                                                                                                  │
│       /Users/dudongcheng/Code/Up/go/src/github.com/six-ddc/v2ex-go/ui.go:390 +0x4b1                                                                             │
main.main.func14(0x6f866c, 0x5, 0xc420079890, 0x9, 0x6f866c, 0x5, 0x0, 0x0, 0x6b6f60, 0xc4200798a0, ...)                                                          │
│       /Users/dudongcheng/Code/Up/go/src/github.com/six-ddc/v2ex-go/main.go:339 +0xf3                                                                            │
github.com/six-ddc/termui.(*EvtStream).Loop.func1(0xc4200740f0, 0x6f866c, 0x5, 0xc420079890, 0x9, 0x6f866c, 0x5, 0x0, 0x0, 0x6b6f60, ...)                         │
│───────/Users/dudongcheng/Code/Up/go/src/github.com/six-ddc/termui/events.go:243 +0xfd───────────────────────────────────────────────────────────────────────────│created by github.com/six-ddc/termui.(*EvtStream).Loop────────────────────────────────────────────────────────────────────────────────────────────────────────────││───────/Users/dudongcheng/Code/Up/go/src/github.com/six-ddc/termui/events.go:245 +0x167───
```
## 截图
![深度截图_选择区域_20180728194354.png](https://i.loli.net/2018/07/28/5b5c570f9c017.png)

**Comment by akkuman** [comment]
linux 386也是一样的报错

**Comment by six-ddc** [comment]
已修复。 @akkuman
